#Версии Zabbix
zabbix_version: "6.0"
zabbix_server_version: "1:6.0.0-1"
zabbix_frontend_version: "1:6.0.0-1"
zabbix_agent_version: "1:6.0.0-1"

# Настройки базы данных
zabbix_db_name: "zabbix"
zabbix_db_user: "zabbix"
zabbix_db_password: "ZabbixPassword2025"
zabbix_db_root_password: "Zabbix1340"

# Настройки сервера Zabbix
zabbix_server_listen_port: 10051
zabbix_server_log_file: "/var/log/zabbix/zabbix_server.log"
zabbix_server_pid_file: "/var/run/zabbix/zabbix_server.pid"

# Настройки агента Zabbix
zabbix_agent_listen_port: 10050
zabbix_agent_log_file: "/var/log/zabbix/zabbix_agent2.log"
zabbix_agent_pid_file: "/var/run/zabbix/zabbix_agent2.pid"
